```{r message = FALSE, warning = FALSE}
# Load packages
library(plyr)
library(fpp3)
library(tsibble)
library(forecast)
library(zoo)
library(dplyr)
library(tidyverse)
library(ggplot2)
library(quantmod)
```

# Exploring Trucking Volume

```{r}

# Let's just import the data
data <- readr::read_csv(file = 'data/data_interpolated_with_volume.csv') %>%
  dplyr::select(-X1) %>%
  dplyr:: filter(Mode == "R" & DRegionDAT == "IL_CHI") %>%
  drop_na() %>%
  mutate(yw = yearweek(yw)) %>%
  relocate(yw, Mode, ORegionDAT, DRegionDAT, approx_cost) %>%
  as_tsibble(key = c(Mode, ORegionDAT, DRegionDAT), index = yw)


data
```


```{r}

# Normalize 
scaled_data <- data %>%
  mutate_at(c("approx_cost", "prcp", "tmax", "volume", "new_deaths"), ~(scale(.) %>% as.vector))
  
# Preview
head(scaled_data)

# Volume with other normalized time series
ggplot() + 
  geom_line(data = scaled_data, aes(x = yw, y = tmax), color = "red") +
  geom_line(data = scaled_data, aes(x = yw, y = prcp), color = "blue") +
  geom_line(data = scaled_data, aes(x = yw, y = approx_cost), color = "black") +
  geom_line(data = scaled_data, aes(x = yw, y = volume), color = "orange") +
  geom_line(data = scaled_data, aes(x = yw, y = new_deaths), color = "green") +
  theme(legend.position="right") +
  labs(title = "Fresno to Chicago Refrigerated", y = "normalized value")

# Volume alone
autoplot(data, volume)
```
```{r}

# Import the data
data <- readr::read_csv(file = 'data/data_interpolated_with_volume.csv') %>%
  dplyr::select(-X1) %>%
  dplyr:: filter(Mode == "R" & DRegionDAT == "IL_CHI") %>%
  drop_na() %>%
  mutate(yw = yearweek(yw)) %>%
  relocate(yw, Mode, ORegionDAT, DRegionDAT, approx_cost)

ggplot(data, aes(x=volume, y=approx_cost)) +
  geom_point(size=2, shape=23)
```



